### PR TITLE
DAC-290 [FE]Result of the broadcasting

### PR DESCRIPTION
**Pull request by amnambiar**
https://input-output.atlassian.net/browse/DAC-290

### CODE REVIEW

**Comment by amnambiar** [comment]
@bogdan-manole , to be reviewed only after https://github.com/input-output-hk/dapps-certification/pull/46 is closed

**Comment by amnambiar** [comment]
@bogdan-manole ready for review

**Review by bogdan-manole — CHANGES_REQUESTED** [review]
I guess, now this branch has to be aligned with the new API interface before it is merged

**Comment by amnambiar** [comment]
@bogdan-manole Changes here doesn't involve 'Get Certificate', instead the network of the wallet is evaluated on 'Connect' itself. So, assuming this can be reviewed/merged upfront

**Pull request merged**
