### PR TITLE
feat: format test runs certification compliant with CIP-0096 ( PLT-6087)

### PR DESCRIPTION
**Pull request by bogdan-manole**
### Summary by CodeRabbit

- New Feature: Introduced Level 1 certification functionality, including new parsers for certification input and issuer information.
- New Feature: Added the ability to optionally include a report content ID in the `Run` data type.
- Refactor: Renamed various routes and functions to reflect the focus on Level 1 certifications.
- New Feature: Modified several functions to accept a `DB.CertificationLevel` parameter, allowing for more flexible certification processes.
- New Feature: Updated `AuditorCertificationInput` and introduced `CertificationInput` types to handle additional certification data.
- New Feature: Enhanced `createCertification` function to handle dry run scenarios, upload certification reports to IPFS, and create certification metadata.
- Chore: Temporarily disabled the `certifyRuns` function.

### CODE REVIEW

**Review by RSoulatIOHK — APPROVED** [review]
You changed the thing about L0, L1, L2, L3, the rest looks good but I haven't tried to compile it.

**Comment by RSoulatIOHK** [comment]
Limit the certificationIssuer to 64 chars

**Comment by RSoulatIOHK** [comment]
Looks good on the code. I'll need to see through the tool usage to be sure

**Comment by amnambiar** [comment]
@bogdan-manole , 
After fixes in FE as per https://github.com/input-output-hk/dapps-certification-web/pull/8#issuecomment-1725318612, 

`POST https://excuse.ro/run/c65be64c-be5b-4761-b0a6-c3da4d6687fa/certificate` failed with error **403** - `DApp subject not available`

```
payload -
{"certificateIssuer":{"name":"test","social":{"contact":"test@test.com","website":"test.com"}},"disclaimer":"test","scripts":[{"scriptHash":"1234567890123456789012345678901234567890123456789012345678901234","smartContractInfo":{"era":null,"compiler":null,"compilerVersion":null,"optimizer":null,"optimizerVersion":null,"progLang":null,"repoUrl":null}}],"subject":"test","summary":"test"}
```

Looks like [CertificationInput](http://swagger.json/#/definitions/CertificationInput) Model doesn't have `subject`(mandatory) in it. This needs to be fixed either in FE or BE. Please check and update

**Pull request merged**
