### PR TITLE
DAC-322: serve logs in local mode

### PR DESCRIPTION
**Pull request by bogdan-manole**

### CODE REVIEW

**Review by shlevy — CHANGES_REQUESTED** [review]
We should either do this properly with eventuo11y, or switch to a different logging mode, not thread through 2 logging mechanisms.

As I mentioned on slack, there's cleanup using better logging interfaces I have slated for next sprint, if you're having trouble navigating the current logging code.

**Review by RSoulatIOHK — APPROVED** [review]
Not really reviewed.

**Review by shlevy — APPROVED** [review]
Approving to unblock for now

**Comment by bogdan-manole** [comment]
these changes will be revisited later ( DAC-356 )

**Pull request merged**
