### PR TITLE
feat/change-profile-fields ( PLT-6187 , PLT-7408)

### PR DESCRIPTION
**Pull request by bogdan-manole**
Fixes [PLT-6187](https://input-output.atlassian.net/browse/PLT-6187)
Fixes [PLT-7408](https://input-output.atlassian.net/browse/PLT-7408)

Summary:

- Modifies/Adds different user details to `Profile`
- Add Pattern(Regex) validation for these fields
- Creates a unique dependent type `PatternedText` encapsulating the regex pattern within the type definition
- Changing `Twitter`,`LinkedIn`,`Website`, etc as aliases for `PatternText`
- Uses these types directly as Selda table fields
- A lot of refactoring involving these changes
- Adding unit tests and property testing regarding these types serialization

### CODE REVIEW

**Review by amnambiar — DISMISSED** [review]
@bogdan-manole Looks like `twitter`, `linkedin` are not set as optional in the `PUT /profile/current`. It failed when they were submitted with `""` values

**Comment by amnambiar** [comment]
@bogdan-manole , 
Bug - the entered details are not saved

Called PUT /profile/current with payload `{"company":"Comp1","email":"comp1test1@test.com","address":"test","city":"test","country":"test","twitter":"test12","linkedin":"https://linkedin.com/in/test"}` . 
Received the response `{"address":"addr_test1qqy3xyv0n4s7fm2ww7yutgzuhvvsf9mvyffmtndmmkg53er3ydg8gsfrl2eh3h26v74qvhyqvj992v7qyvqqrk2pf4kqaaahsu","authors":null,"contacts":null,"dapp":null,"linkedin":"https://linkedin.com/in/test","twitter":"test12","vendor":null,"website":null}`

Logout of the tool. 
Login again. 

Called GET /profile/current and received response `{"address":"addr_test1qqy3xyv0n4s7fm2ww7yutgzuhvvsf9mvyffmtndmmkg53er3ydg8gsfrl2eh3h26v74qvhyqvj992v7qyvqqrk2pf4kqaaahsu","authors":null,"contacts":null,"dapp":null,"linkedin":"https://linkedin.com/in/test","twitter":"test12","vendor":null,"website":null}`

**Comment by bogdan-manole** [comment]
> @bogdan-manole Looks like `twitter`, `linkedin` are not set as optional in the `PUT /profile/current`. It failed when they were submitted with `""` values

`""` does not represent `null` or the key missing, it's the empty string and doesn't match the required regex `^[A-Za-z0-9_]{1,15}$` . Please take a look at the ProfileBody model and the regex validators, and let's align the BE and FE

**Review by RSoulatIOHK — APPROVED** [review]
Approved

**Pull request merged**
