### PR TITLE
PLT-7786: Kubernetes scheduler

### PR DESCRIPTION
**Pull request by shlevy**
This enables running with a kubernetes-powered job backend, enabled when passing `--run-certify-image` to specify the docker container containing `run-certify`.

### CODE REVIEW

**Comment by shlevy** [comment]
This is on top of #132.

This PR is designed to be reviewed commit by commit.

**Comment by shlevy** [comment]
Deployed in https://github.com/input-output-hk/dapps-certification/commit/c3b27b3bc05016c265f7da9084cb35578a6d2dd1

**Comment by bogdan-manole** [comment]
I guess this needs some rebasing

**Comment by shlevy** [comment]
Hmm, how did you merge the other PR? This is one reason why a merge with a proper merge commit is the right way to go.

Will rebase.

**Comment by shlevy** [comment]
Rebased

**Review by bogdan-manole — APPROVED** [review]
I haven't a local dev env for Kubernetes, but `--local` mode still works, and the vela deployment works in most of the cases. Sometimes when the test jobs are running we get an error but I guess it's related to the cluster infrastructure

**Comment by bogdan-manole** [comment]
> Hmm, how did you merge the other PR? This is one reason why a merge with a proper merge commit is the right way to go.
> 
> Will rebase.

for some time we used the fast-forward method ( and also by formatting the branch commits according to conventional commits specifications)

**Pull request merged**
